In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,accuracy_score
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix
from sklearn import preprocessing
from sklearn import utils
import warnings

In [2]:
df=pd.read_csv("expanded_student_attendance_dataset.csv")

In [3]:
print(df)

     Student_ID  Class_Participation  Previous_Attendance_Rate  \
0             1                    4                        61
1             2                    5                        93
2             3                    3                        85
3             4                    5                        97
4             5                    5                        53
..          ...                  ...                       ...
995         996                    2                        82
996         997                    1                        98
997         998                    1                       100
998         999                    4                        63
999        1000                    3                        61

     Average_Grades  Engagement_in_Activities  Distance_from_School  \
0                91                         5                  8.13
1                69                         5                 12.68
2                99                         2                 26.94
3                73                         4                  1.01
4                92                         2                 27.14
..              ...                       ...                   ...
995              56                         2                 17.16
996              71                         4                  5.53
997              82                         2                 25.20
998              66                         3                 11.39
999              73                         5                 27.47

     Current_Attendance
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
995                   1
996                   1
997                   0
998                   1
999                   1

[1000 rows x 7 columns]

In [4]:
df.head()

,Student_ID,Class_Participation,Previous_Attendance_Rate,Average_Grades,Engagement_in_Activities,Distance_from_School,Current_Attendance
0,1,4,61,91,5,8.13,1
1,2,5,93,69,5,12.68,1
2,3,3,85,99,2,26.94,1
3,4,5,97,73,4,1.01,1
4,5,5,53,92,2,27.14,1

In [5]:
df.shape

(1000, 7)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Student_ID                1000 non-null   int64
 1   Class_Participation       1000 non-null   int64
 2   Previous_Attendance_Rate  1000 non-null   int64
 3   Average_Grades            1000 non-null   int64
 4   Engagement_in_Activities  1000 non-null   int64
 5   Distance_from_School      1000 non-null   float64
 6   Current_Attendance        1000 non-null   int64
dtypes: float64(1), int64(6)
memory usage: 54.8 KB

In [7]:
df.describe()

,Student_ID,Class_Participation,Previous_Attendance_Rate,Average_Grades,Engagement_in_Activities,Distance_from_School,Current_Attendance
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,3.004000,75.440000,74.712000,3.033000,15.837730,0.901000
std,288.819436,1.433192,14.615951,14.534452,1.414182,8.265205,0.298811
min,1.000000,1.000000,50.000000,50.000000,1.000000,1.010000,0.000000
25%,250.750000,2.000000,63.000000,62.750000,2.000000,8.907500,1.000000
50%,500.500000,3.000000,76.000000,74.000000,3.000000,16.075000,1.000000
75%,750.250000,4.000000,88.000000,87.000000,4.000000,22.992500,1.000000
max,1000.000000,5.000000,100.000000,100.000000,5.000000,29.990000,1.000000

In [8]:
df.isna().sum()

Student_ID                  0
Class_Participation         0
Previous_Attendance_Rate    0
Average_Grades              0
Engagement_in_Activities    0
Distance_from_School        0
Current_Attendance          0
dtype: int64

In [9]:
df.corr()

,Student_ID,Class_Participation,Previous_Attendance_Rate,Average_Grades,Engagement_in_Activities,Distance_from_School,Current_Attendance
Student_ID,1.000000,0.008885,-0.030596,0.010607,0.004699,0.017229,0.014562
Class_Participation,0.008885,1.000000,0.040009,0.055510,-0.048466,-0.064862,0.379584
Previous_Attendance_Rate,-0.030596,0.040009,1.000000,-0.020013,-0.002543,0.036201,0.057657
Average_Grades,0.010607,0.055510,-0.020013,1.000000,0.004846,0.019867,0.048283
Engagement_in_Activities,0.004699,-0.048466,-0.002543,0.004846,1.000000,-0.015444,0.154606
Distance_from_School,0.017229,-0.064862,0.036201,0.019867,-0.015444,1.000000,-0.366253
Current_Attendance,0.014562,0.379584,0.057657,0.048283,0.154606,-0.366253,1.000000

In [10]:
x=df[["Student_ID"]]
y=df[["Current_Attendance"]]

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [12]:
slr=LinearRegression()
slr.fit(x_train,y_train)

LinearRegression()

In [13]:
ypred=slr.predict(x_test)
ypred

array([[0.88365507],
       [0.90251901],
       [0.90580446],
       [0.89071878],
       [0.90794   ],
       [0.90065726],
       [0.90131435],
       [0.89047237],
       [0.90673533],
       [0.89008907],
       [0.88639294],
       [0.90876136],
       [0.8967421 ],
       [0.90421649],
       [0.90618776],
       [0.90016444],
       [0.90282017],
       [0.90134172],
       [0.89392209],
       [0.88458595],
       [0.88847372],
       [0.88447643],
       [0.88896654],
       [0.90607824],
       [0.88803566],
       [0.90013706],
       [0.89293646],
       [0.88789877],
       [0.88535255],
       [0.90120483],
       [0.90043823],
       [0.88874751],
       [0.88825469],
       [0.90312134],
       [0.89529103],
       [0.88663935],
       [0.88318963],
       [0.90720077],
       [0.89759084],
       [0.90032871],
       [0.90145124],
       [0.90824116],
       [0.90511999],
       [0.89778249],
       [0.89876812],
       [0.89277218],
       [0.89895977],
       [0.9068996 ],
       [0.90438076],
       [0.90763883],
       [0.88305274],
       [0.90336775],
       [0.89479821],
       [0.89167703],
       [0.90648892],
       [0.90958272],
       [0.8975087 ],
       [0.89701589],
       [0.88713217],
       [0.90626989],
       [0.88762498],
       [0.90802213],
       [0.88540731],
       [0.89846696],
       [0.88770712],
       [0.88450381],
       [0.89947997],
       [0.89767297],
       [0.89189606],
       [0.891458  ],
       [0.89028072],
       [0.89052713],
       [0.88951412],
       [0.90750194],
       [0.88910343],
       [0.89655045],
       [0.90224522],
       [0.90813165],
       [0.88893916],
       [0.89964424],
       [0.90254639],
       [0.88899392],
       [0.90542115],
       [0.89383995],
       [0.9044629 ],
       [0.88655721],
       [0.90744718],
       [0.89904191],
       [0.88809042],
       [0.88442167],
       [0.88754285],
       [0.8903081 ],
       [0.9053664 ],
       [0.90295707],
       [0.8953184 ],
       [0.88696789],
       [0.90221784],
       [0.90676271],
       [0.90520212],
       [0.89682423],
       [0.90052036],
       [0.88970577],
       [0.90867922],
       [0.89348403],
       [0.897892  ],
       [0.90547591],
       [0.89446966],
       [0.89430539],
       [0.89693375],
       [0.89644093],
       [0.90268328],
       [0.9017524 ],
       [0.88283371],
       [0.90761145],
       [0.89852172],
       [0.88792615],
       [0.90156075],
       [0.89786463],
       [0.90139648],
       [0.90564018],
       [0.89389471],
       [0.89537316],
       [0.90930893],
       [0.90082153],
       [0.88995217],
       [0.88844635],
       [0.90692698],
       [0.89422326],
       [0.89066402],
       [0.90528426],
       [0.90495572],
       [0.90487358],
       [0.89939783],
       [0.90643417],
       [0.90049298],
       [0.88507876],
       [0.88650246],
       [0.89408636],
       [0.89112946],
       [0.90271066],
       [0.89581122],
       [0.88918557],
       [0.88455857],
       [0.89290908],
       [0.89118422],
       [0.89353879],
       [0.89509937],
       [0.89258053],
       [0.90531164],
       [0.90585921],
       [0.89945259],
       [0.90807689],
       [0.89351141],
       [0.89482559],
       [0.89397685],
       [0.89301859],
       [0.89060926],
       [0.88466808],
       [0.88882965],
       [0.89594812],
       [0.89175917],
       [0.88494187],
       [0.89578384],
       [0.90164289],
       [0.89041761],
       [0.88836421],
       [0.88652983],
       [0.88948674],
       [0.90796737],
       [0.8923615 ],
       [0.8984122 ],
       [0.893265  ],
       [0.89728967],
       [0.90533902],
       [0.89534578],
       [0.88266943],
       [0.88765236],
       [0.88562634],
       [0.88702265],
       [0.90829592],
       [0.9048462 ],
       [0.89444229],
       [0.89334714],
       [0.90731029],
       [0.8873512 ],
       [0.88614653],
       [0.90459979],
       [0.90449028],
       [0.90397008],
       [0.88726906],
       [0.89589336],
       [0.89498986],
       [0.89843958],
       [0.88475022],
       [0.89838482],
       [0.9056128 ],
       [0.90481882],
       [0.90810427],
       [0.89950735],
       [0.90479144]])

In [14]:
r2_score(y_test,ypred)

-0.010653611394629614

In [15]:
warnings.filterwarnings("ignore")

In [16]:
x_new=np.array([5000]).reshape(1,-1)
slr.predict(x_new)

array([[1.01950829]])

In [17]:
x=df[["Student_ID"]]
y=df[["Current_Attendance"]]

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [19]:
knn=KNeighborsClassifier(n_neighbors=3,metric='euclidean')
knn.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [20]:
ypred=knn.predict(x_test)
ypred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [21]:
accuracy_score(y_test,ypred)

0.905

In [22]:
x_new=np.array([5000]).reshape(-1, 1)
slr.predict(x_new)

array([[1.01950829]])

In [23]:
x=df[["Student_ID"]]
y=df[["Current_Attendance"]]

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [25]:
classifier=LinearSVC()
classifier.fit(x_train,y_train)

LinearSVC()

In [26]:
ypred=classifier.predict(x_test)
ypred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [27]:
accuracy_score(y_test,ypred)

0.92

In [28]:
x_new=np.array([5000]).reshape(-1, 1)
classifier.predict(x_new)

array([1])