In [10]:
import pandas as pd
import numpy as np

In [12]:
df=pd.read_csv("Iris.csv")

In [14]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [16]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [20]:
df["Species"].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [22]:
df1=df.copy(deep=True)
mapping={"Iris-setosa":3,"Iris-versicolor":2,"Iris-virginica":1}
df1["Species"]=df1["Species"].map(mapping)

In [24]:
df1.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        3
1   2            4.9           3.0            1.4           0.2        3
2   3            4.7           3.2            1.3           0.2        3
3   4            4.6           3.1            1.5           0.2        3
4   5            5.0           3.6            1.4           0.2        3

In [32]:
df2=df.copy(deep=True)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(df2["Species"])
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [38]:
df3=df.copy(deep=True)
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
x3=df[["Species"]]
ohe.fit_transform(x3).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [44]:
pd.get_dummies(df3["Species"])

     Iris-setosa  Iris-versicolor  Iris-virginica
0           True            False           False
1           True            False           False
2           True            False           False
3           True            False           False
4           True            False           False
..           ...              ...             ...
145        False            False            True
146        False            False            True
147        False            False            True
148        False            False            True
149        False            False            True

[150 rows x 3 columns]

In [54]:
from sklearn.preprocessing import MinMaxScaler
df4=df.copy(deep=True)
x4=df4.iloc[:,0:5]
mms=MinMaxScaler(feature_range=(0,2))
x4_Scaled=mms.fit_transform(x4)
x4_Scaled

array([[0.        , 0.44444444, 1.25      , 0.13559322, 0.08333333],
       [0.01342282, 0.33333333, 0.83333333, 0.13559322, 0.08333333],
       [0.02684564, 0.22222222, 1.        , 0.10169492, 0.08333333],
       [0.04026846, 0.16666667, 0.91666667, 0.16949153, 0.08333333],
       [0.05369128, 0.38888889, 1.33333333, 0.13559322, 0.08333333],
       [0.06711409, 0.61111111, 1.58333333, 0.23728814, 0.25      ],
       [0.08053691, 0.16666667, 1.16666667, 0.13559322, 0.16666667],
       [0.09395973, 0.38888889, 1.16666667, 0.16949153, 0.08333333],
       [0.10738255, 0.05555556, 0.75      , 0.13559322, 0.08333333],
       [0.12080537, 0.33333333, 0.91666667, 0.16949153, 0.        ],
       [0.13422819, 0.61111111, 1.41666667, 0.16949153, 0.08333333],
       [0.14765101, 0.27777778, 1.16666667, 0.20338983, 0.08333333],
       [0.16107383, 0.27777778, 0.83333333, 0.13559322, 0.        ],
       [0.17449664, 0.        , 0.83333333, 0.03389831, 0.        ],
       [0.18791946, 0.83333333, 1.66666667, 0.06779661, 0.08333333],
       [0.20134228, 0.77777778, 2.        , 0.16949153, 0.25      ],
       [0.2147651 , 0.61111111, 1.58333333, 0.10169492, 0.25      ],
       [0.22818792, 0.44444444, 1.25      , 0.13559322, 0.16666667],
       [0.24161074, 0.77777778, 1.5       , 0.23728814, 0.16666667],
       [0.25503356, 0.44444444, 1.5       , 0.16949153, 0.16666667],
       [0.26845638, 0.61111111, 1.16666667, 0.23728814, 0.08333333],
       [0.28187919, 0.44444444, 1.41666667, 0.16949153, 0.25      ],
       [0.29530201, 0.16666667, 1.33333333, 0.        , 0.08333333],
       [0.30872483, 0.44444444, 1.08333333, 0.23728814, 0.33333333],
       [0.32214765, 0.27777778, 1.16666667, 0.30508475, 0.08333333],
       [0.33557047, 0.38888889, 0.83333333, 0.20338983, 0.08333333],
       [0.34899329, 0.38888889, 1.16666667, 0.20338983, 0.25      ],
       [0.36241611, 0.5       , 1.25      , 0.16949153, 0.08333333],
       [0.37583893, 0.5       , 1.16666667, 0.13559322, 0.08333333],
       [0.38926174, 0.22222222, 1.        , 0.20338983, 0.08333333],
       [0.40268456, 0.27777778, 0.91666667, 0.20338983, 0.08333333],
       [0.41610738, 0.61111111, 1.16666667, 0.16949153, 0.25      ],
       [0.4295302 , 0.5       , 1.75      , 0.16949153, 0.        ],
       [0.44295302, 0.66666667, 1.83333333, 0.13559322, 0.08333333],
       [0.45637584, 0.33333333, 0.91666667, 0.16949153, 0.        ],
       [0.46979866, 0.38888889, 1.        , 0.06779661, 0.08333333],
       [0.48322148, 0.66666667, 1.25      , 0.10169492, 0.08333333],
       [0.4966443 , 0.33333333, 0.91666667, 0.16949153, 0.        ],
       [0.51006711, 0.05555556, 0.83333333, 0.10169492, 0.08333333],
       [0.52348993, 0.44444444, 1.16666667, 0.16949153, 0.08333333],
       [0.53691275, 0.38888889, 1.25      , 0.10169492, 0.16666667],
       [0.55033557, 0.11111111, 0.25      , 0.10169492, 0.16666667],
       [0.56375839, 0.05555556, 1.        , 0.10169492, 0.08333333],
       [0.57718121, 0.38888889, 1.25      , 0.20338983, 0.41666667],
       [0.59060403, 0.44444444, 1.5       , 0.30508475, 0.25      ],
       [0.60402685, 0.27777778, 0.83333333, 0.13559322, 0.16666667],
       [0.61744966, 0.44444444, 1.5       , 0.20338983, 0.08333333],
       [0.63087248, 0.16666667, 1.        , 0.13559322, 0.08333333],
       [0.6442953 , 0.55555556, 1.41666667, 0.16949153, 0.08333333],
       [0.65771812, 0.38888889, 1.08333333, 0.13559322, 0.08333333],
       [0.67114094, 1.5       , 1.        , 1.25423729, 1.08333333],
       [0.68456376, 1.16666667, 1.        , 1.18644068, 1.16666667],
       [0.69798658, 1.44444444, 0.91666667, 1.3220339 , 1.16666667],
       [0.7114094 , 0.66666667, 0.25      , 1.01694915, 1.        ],
       [0.72483221, 1.22222222, 0.66666667, 1.22033898, 1.16666667],
       [0.73825503, 0.77777778, 0.66666667, 1.18644068, 1.        ],
       [0.75167785, 1.11111111, 1.08333333, 1.25423729, 1.25      ],
       [0.76510067, 0.33333333, 0.33333333, 0.77966102, 0.75      ],
       [0.77852349, 1.27777778, 0.75      , 1.22033898, 1.        ],
       [0.79194631, 0.5       , 0.58333333, 0.98305085, 1.08333333],
       [0.80536913, 0.38888889, 0.        , 0.84745763, 0.75      ],
       [0.81879195, 0.88888889, 0.83333333, 1.08474576, 1.16666667],
       [0.83221477, 0.94444444, 0.16666667, 1.01694915, 0.75      ],
       [0.84563758, 1.        , 0.75      , 1.25423729, 1.08333333],
       [0.8590604 , 0.72222222, 0.75      , 0.88135593, 1.        ],
       [0.87248322, 1.33333333, 0.91666667, 1.15254237, 1.08333333],
       [0.88590604, 0.72222222, 0.83333333, 1.18644068, 1.16666667],
       [0.89932886, 0.83333333, 0.58333333, 1.05084746, 0.75      ],
       [0.91275168, 1.05555556, 0.16666667, 1.18644068, 1.16666667],
       [0.9261745 , 0.72222222, 0.41666667, 0.98305085, 0.83333333],
       [0.93959732, 0.88888889, 1.        , 1.28813559, 1.41666667],
       [0.95302013, 1.        , 0.66666667, 1.01694915, 1.        ],
       [0.96644295, 1.11111111, 0.41666667, 1.3220339 , 1.16666667],
       [0.97986577, 1.        , 0.66666667, 1.25423729, 0.91666667],
       [0.99328859, 1.16666667, 0.75      , 1.11864407, 1.        ],
       [1.00671141, 1.27777778, 0.83333333, 1.15254237, 1.08333333],
       [1.02013423, 1.38888889, 0.66666667, 1.28813559, 1.08333333],
       [1.03355705, 1.33333333, 0.83333333, 1.3559322 , 1.33333333],
       [1.04697987, 0.94444444, 0.75      , 1.18644068, 1.16666667],
       [1.06040268, 0.77777778, 0.5       , 0.84745763, 0.75      ],
       [1.0738255 , 0.66666667, 0.33333333, 0.94915254, 0.83333333],
       [1.08724832, 0.66666667, 0.33333333, 0.91525424, 0.75      ],
       [1.10067114, 0.83333333, 0.58333333, 0.98305085, 0.91666667],
       [1.11409396, 0.94444444, 0.58333333, 1.38983051, 1.25      ],
       [1.12751678, 0.61111111, 0.83333333, 1.18644068, 1.16666667],
       [1.1409396 , 0.94444444, 1.16666667, 1.18644068, 1.25      ],
       [1.15436242, 1.33333333, 0.91666667, 1.25423729, 1.16666667],
       [1.16778523, 1.11111111, 0.25      , 1.15254237, 1.        ],
       [1.18120805, 0.72222222, 0.83333333, 1.05084746, 1.        ],
       [1.19463087, 0.66666667, 0.41666667, 1.01694915, 1.        ],
       [1.20805369, 0.66666667, 0.5       , 1.15254237, 0.91666667],
       [1.22147651, 1.        , 0.83333333, 1.22033898, 1.08333333],
       [1.23489933, 0.83333333, 0.5       , 1.01694915, 0.91666667],
       [1.24832215, 0.38888889, 0.25      , 0.77966102, 0.75      ],
       [1.26174497, 0.72222222, 0.58333333, 1.08474576, 1.        ],
       [1.27516779, 0.77777778, 0.83333333, 1.08474576, 0.91666667],
       [1.2885906 , 0.77777778, 0.75      , 1.08474576, 1.        ],
       [1.30201342, 1.05555556, 0.75      , 1.11864407, 1.        ],
       [1.31543624, 0.44444444, 0.41666667, 0.6779661 , 0.83333333],
       [1.32885906, 0.77777778, 0.66666667, 1.05084746, 1.        ],
       [1.34228188, 1.11111111, 1.08333333, 1.69491525, 2.        ],
       [1.3557047 , 0.83333333, 0.58333333, 1.38983051, 1.5       ],
       [1.36912752, 1.55555556, 0.83333333, 1.66101695, 1.66666667],
       [1.38255034, 1.11111111, 0.75      , 1.55932203, 1.41666667],
       [1.39597315, 1.22222222, 0.83333333, 1.62711864, 1.75      ],
       [1.40939597, 1.83333333, 0.83333333, 1.89830508, 1.66666667],
       [1.42281879, 0.33333333, 0.41666667, 1.18644068, 1.33333333],
       [1.43624161, 1.66666667, 0.75      , 1.79661017, 1.41666667],
       [1.44966443, 1.33333333, 0.41666667, 1.62711864, 1.41666667],
       [1.46308725, 1.61111111, 1.33333333, 1.72881356, 2.        ],
       [1.47651007, 1.22222222, 1.        , 1.38983051, 1.58333333],
       [1.48993289, 1.16666667, 0.58333333, 1.45762712, 1.5       ],
       [1.5033557 , 1.38888889, 0.83333333, 1.52542373, 1.66666667],
       [1.51677852, 0.77777778, 0.41666667, 1.3559322 , 1.58333333],
       [1.53020134, 0.83333333, 0.66666667, 1.38983051, 1.91666667],
       [1.54362416, 1.16666667, 1.        , 1.45762712, 1.83333333],
       [1.55704698, 1.22222222, 0.83333333, 1.52542373, 1.41666667],
       [1.5704698 , 1.88888889, 1.5       , 1.93220339, 1.75      ],
       [1.58389262, 1.88888889, 0.5       , 2.        , 1.83333333],
       [1.59731544, 0.94444444, 0.16666667, 1.3559322 , 1.16666667],
       [1.61073826, 1.44444444, 1.        , 1.59322034, 1.83333333],
       [1.62416107, 0.72222222, 0.66666667, 1.3220339 , 1.58333333],
       [1.63758389, 1.88888889, 0.66666667, 1.93220339, 1.58333333],
       [1.65100671, 1.11111111, 0.58333333, 1.3220339 , 1.41666667],
       [1.66442953, 1.33333333, 1.08333333, 1.59322034, 1.66666667],
       [1.67785235, 1.61111111, 1.        , 1.69491525, 1.41666667],
       [1.69127517, 1.05555556, 0.66666667, 1.28813559, 1.41666667],
       [1.70469799, 1.        , 0.83333333, 1.3220339 , 1.41666667],
       [1.71812081, 1.16666667, 0.66666667, 1.55932203, 1.66666667],
       [1.73154362, 1.61111111, 0.83333333, 1.62711864, 1.25      ],
       [1.74496644, 1.72222222, 0.66666667, 1.72881356, 1.5       ],
       [1.75838926, 2.        , 1.5       , 1.83050847, 1.58333333],
       [1.77181208, 1.16666667, 0.66666667, 1.55932203, 1.75      ],
       [1.7852349 , 1.11111111, 0.66666667, 1.38983051, 1.16666667],
       [1.79865772, 1.        , 0.5       , 1.55932203, 1.08333333],
       [1.81208054, 1.88888889, 0.83333333, 1.72881356, 1.83333333],
       [1.82550336, 1.11111111, 1.16666667, 1.55932203, 1.91666667],
       [1.83892617, 1.16666667, 0.91666667, 1.52542373, 1.41666667],
       [1.85234899, 0.94444444, 0.83333333, 1.28813559, 1.41666667],
       [1.86577181, 1.44444444, 0.91666667, 1.49152542, 1.66666667],
       [1.87919463, 1.33333333, 0.91666667, 1.55932203, 1.91666667],
       [1.89261745, 1.44444444, 0.91666667, 1.38983051, 1.83333333],
       [1.90604027, 0.83333333, 0.58333333, 1.38983051, 1.5       ],
       [1.91946309, 1.38888889, 1.        , 1.66101695, 1.83333333],
       [1.93288591, 1.33333333, 1.08333333, 1.59322034, 2.        ],
       [1.94630872, 1.33333333, 0.83333333, 1.42372881, 1.83333333],
       [1.95973154, 1.11111111, 0.41666667, 1.3559322 , 1.5       ],
       [1.97315436, 1.22222222, 0.83333333, 1.42372881, 1.58333333],
       [1.98657718, 1.05555556, 1.16666667, 1.49152542, 1.83333333],
       [2.        , 0.88888889, 0.83333333, 1.38983051, 1.41666667]])

In [60]:
from sklearn.preprocessing import StandardScaler
df5=df.copy(deep=True)
x5=df5.iloc[:,0:5]
scaler=StandardScaler()
x5_Scaled=scaler.fit_transform(x5)
x5_Scaled

array([[-1.72054204e+00, -9.00681170e-01,  1.03205722e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-1.69744751e+00, -1.14301691e+00, -1.24957601e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.67435299e+00, -1.38535265e+00,  3.37848329e-01,
        -1.39813811e+00, -1.31297673e+00],
       [-1.65125846e+00, -1.50652052e+00,  1.06445364e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-1.62816394e+00, -1.02184904e+00,  1.26346019e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-1.60506942e+00, -5.37177559e-01,  1.95766909e+00,
        -1.17067529e+00, -1.05003079e+00],
       [-1.58197489e+00, -1.50652052e+00,  8.00654259e-01,
        -1.34127240e+00, -1.18150376e+00],
       [-1.55888037e+00, -1.02184904e+00,  8.00654259e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-1.53578584e+00, -1.74885626e+00, -3.56360566e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.51269132e+00, -1.14301691e+00,  1.06445364e-01,
        -1.28440670e+00, -1.44444970e+00],
       [-1.48959680e+00, -5.37177559e-01,  1.49486315e+00,
        -1.28440670e+00, -1.31297673e+00],
       [-1.46650227e+00, -1.26418478e+00,  8.00654259e-01,
        -1.22754100e+00, -1.31297673e+00],
       [-1.44340775e+00, -1.26418478e+00, -1.24957601e-01,
        -1.34127240e+00, -1.44444970e+00],
       [-1.42031323e+00, -1.87002413e+00, -1.24957601e-01,
        -1.51186952e+00, -1.44444970e+00],
       [-1.39721870e+00, -5.25060772e-02,  2.18907205e+00,
        -1.45500381e+00, -1.31297673e+00],
       [-1.37412418e+00, -1.73673948e-01,  3.11468391e+00,
        -1.28440670e+00, -1.05003079e+00],
       [-1.35102965e+00, -5.37177559e-01,  1.95766909e+00,
        -1.39813811e+00, -1.05003079e+00],
       [-1.32793513e+00, -9.00681170e-01,  1.03205722e+00,
        -1.34127240e+00, -1.18150376e+00],
       [-1.30484061e+00, -1.73673948e-01,  1.72626612e+00,
        -1.17067529e+00, -1.18150376e+00],
       [-1.28174608e+00, -9.00681170e-01,  1.72626612e+00,
        -1.28440670e+00, -1.18150376e+00],
       [-1.25865156e+00, -5.37177559e-01,  8.00654259e-01,
        -1.17067529e+00, -1.31297673e+00],
       [-1.23555703e+00, -9.00681170e-01,  1.49486315e+00,
        -1.28440670e+00, -1.05003079e+00],
       [-1.21246251e+00, -1.50652052e+00,  1.26346019e+00,
        -1.56873522e+00, -1.31297673e+00],
       [-1.18936799e+00, -9.00681170e-01,  5.69251294e-01,
        -1.17067529e+00, -9.18557817e-01],
       [-1.16627346e+00, -1.26418478e+00,  8.00654259e-01,
        -1.05694388e+00, -1.31297673e+00],
       [-1.14317894e+00, -1.02184904e+00, -1.24957601e-01,
        -1.22754100e+00, -1.31297673e+00],
       [-1.12008441e+00, -1.02184904e+00,  8.00654259e-01,
        -1.22754100e+00, -1.05003079e+00],
       [-1.09698989e+00, -7.79513300e-01,  1.03205722e+00,
        -1.28440670e+00, -1.31297673e+00],
       [-1.07389537e+00, -7.79513300e-01,  8.00654259e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.05080084e+00, -1.38535265e+00,  3.37848329e-01,
        -1.22754100e+00, -1.31297673e+00],
       [-1.02770632e+00, -1.26418478e+00,  1.06445364e-01,
        -1.22754100e+00, -1.31297673e+00],
       [-1.00461179e+00, -5.37177559e-01,  8.00654259e-01,
        -1.28440670e+00, -1.05003079e+00],
       [-9.81517269e-01, -7.79513300e-01,  2.42047502e+00,
        -1.28440670e+00, -1.44444970e+00],
       [-9.58422745e-01, -4.16009689e-01,  2.65187798e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-9.35328221e-01, -1.14301691e+00,  1.06445364e-01,
        -1.28440670e+00, -1.44444970e+00],
       [-9.12233697e-01, -1.02184904e+00,  3.37848329e-01,
        -1.45500381e+00, -1.31297673e+00],
       [-8.89139173e-01, -4.16009689e-01,  1.03205722e+00,
        -1.39813811e+00, -1.31297673e+00],
       [-8.66044649e-01, -1.14301691e+00,  1.06445364e-01,
        -1.28440670e+00, -1.44444970e+00],
       [-8.42950125e-01, -1.74885626e+00, -1.24957601e-01,
        -1.39813811e+00, -1.31297673e+00],
       [-8.19855601e-01, -9.00681170e-01,  8.00654259e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-7.96761077e-01, -1.02184904e+00,  1.03205722e+00,
        -1.39813811e+00, -1.18150376e+00],
       [-7.73666553e-01, -1.62768839e+00, -1.74477836e+00,
        -1.39813811e+00, -1.18150376e+00],
       [-7.50572030e-01, -1.74885626e+00,  3.37848329e-01,
        -1.39813811e+00, -1.31297673e+00],
       [-7.27477506e-01, -1.02184904e+00,  1.03205722e+00,
        -1.22754100e+00, -7.87084847e-01],
       [-7.04382982e-01, -9.00681170e-01,  1.72626612e+00,
        -1.05694388e+00, -1.05003079e+00],
       [-6.81288458e-01, -1.26418478e+00, -1.24957601e-01,
        -1.34127240e+00, -1.18150376e+00],
       [-6.58193934e-01, -9.00681170e-01,  1.72626612e+00,
        -1.22754100e+00, -1.31297673e+00],
       [-6.35099410e-01, -1.50652052e+00,  3.37848329e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-6.12004886e-01, -6.58345429e-01,  1.49486315e+00,
        -1.28440670e+00, -1.31297673e+00],
       [-5.88910362e-01, -1.02184904e+00,  5.69251294e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-5.65815838e-01,  1.40150837e+00,  3.37848329e-01,
         5.35295827e-01,  2.64698913e-01],
       [-5.42721314e-01,  6.74501145e-01,  3.37848329e-01,
         4.21564419e-01,  3.96171883e-01],
       [-5.19626790e-01,  1.28034050e+00,  1.06445364e-01,
         6.49027235e-01,  3.96171883e-01],
       [-4.96532266e-01, -4.16009689e-01, -1.74477836e+00,
         1.37235899e-01,  1.33225943e-01],
       [-4.73437742e-01,  7.95669016e-01, -5.87763531e-01,
         4.78430123e-01,  3.96171883e-01],
       [-4.50343218e-01, -1.73673948e-01, -5.87763531e-01,
         4.21564419e-01,  1.33225943e-01],
       [-4.27248694e-01,  5.53333275e-01,  5.69251294e-01,
         5.35295827e-01,  5.27644853e-01],
       [-4.04154170e-01, -1.14301691e+00, -1.51337539e+00,
        -2.60824029e-01, -2.61192967e-01],
       [-3.81059646e-01,  9.16836886e-01, -3.56360566e-01,
         4.78430123e-01,  1.33225943e-01],
       [-3.57965122e-01, -7.79513300e-01, -8.19166497e-01,
         8.03701950e-02,  2.64698913e-01],
       [-3.34870598e-01, -1.02184904e+00, -2.43898725e+00,
        -1.47092621e-01, -2.61192967e-01],
       [-3.11776074e-01,  6.86617933e-02, -1.24957601e-01,
         2.50967307e-01,  3.96171883e-01],
       [-2.88681550e-01,  1.89829664e-01, -1.97618132e+00,
         1.37235899e-01, -2.61192967e-01],
       [-2.65587026e-01,  3.10997534e-01, -3.56360566e-01,
         5.35295827e-01,  2.64698913e-01],
       [-2.42492502e-01, -2.94841818e-01, -3.56360566e-01,
        -9.02269170e-02,  1.33225943e-01],
       [-2.19397978e-01,  1.03800476e+00,  1.06445364e-01,
         3.64698715e-01,  2.64698913e-01],
       [-1.96303454e-01, -2.94841818e-01, -1.24957601e-01,
         4.21564419e-01,  3.96171883e-01],
       [-1.73208930e-01, -5.25060772e-02, -8.19166497e-01,
         1.94101603e-01, -2.61192967e-01],
       [-1.50114406e-01,  4.32165405e-01, -1.97618132e+00,
         4.21564419e-01,  3.96171883e-01],
       [-1.27019882e-01, -2.94841818e-01, -1.28197243e+00,
         8.03701950e-02, -1.29719997e-01],
       [-1.03925358e-01,  6.86617933e-02,  3.37848329e-01,
         5.92161531e-01,  7.90590793e-01],
       [-8.08308339e-02,  3.10997534e-01, -5.87763531e-01,
         1.37235899e-01,  1.33225943e-01],
       [-5.77363100e-02,  5.53333275e-01, -1.28197243e+00,
         6.49027235e-01,  3.96171883e-01],
       [-3.46417860e-02,  3.10997534e-01, -5.87763531e-01,
         5.35295827e-01,  1.75297293e-03],
       [-1.15472620e-02,  6.74501145e-01, -3.56360566e-01,
         3.07833011e-01,  1.33225943e-01],
       [ 1.15472620e-02,  9.16836886e-01, -1.24957601e-01,
         3.64698715e-01,  2.64698913e-01],
       [ 3.46417860e-02,  1.15917263e+00, -5.87763531e-01,
         5.92161531e-01,  2.64698913e-01],
       [ 5.77363100e-02,  1.03800476e+00, -1.24957601e-01,
         7.05892939e-01,  6.59117823e-01],
       [ 8.08308339e-02,  1.89829664e-01, -3.56360566e-01,
         4.21564419e-01,  3.96171883e-01],
       [ 1.03925358e-01, -1.73673948e-01, -1.05056946e+00,
        -1.47092621e-01, -2.61192967e-01],
       [ 1.27019882e-01, -4.16009689e-01, -1.51337539e+00,
         2.35044910e-02, -1.29719997e-01],
       [ 1.50114406e-01, -4.16009689e-01, -1.51337539e+00,
        -3.33612130e-02, -2.61192967e-01],
       [ 1.73208930e-01, -5.25060772e-02, -8.19166497e-01,
         8.03701950e-02,  1.75297293e-03],
       [ 1.96303454e-01,  1.89829664e-01, -8.19166497e-01,
         7.62758643e-01,  5.27644853e-01],
       [ 2.19397978e-01, -5.37177559e-01, -1.24957601e-01,
         4.21564419e-01,  3.96171883e-01],
       [ 2.42492502e-01,  1.89829664e-01,  8.00654259e-01,
         4.21564419e-01,  5.27644853e-01],
       [ 2.65587026e-01,  1.03800476e+00,  1.06445364e-01,
         5.35295827e-01,  3.96171883e-01],
       [ 2.88681550e-01,  5.53333275e-01, -1.74477836e+00,
         3.64698715e-01,  1.33225943e-01],
       [ 3.11776074e-01, -2.94841818e-01, -1.24957601e-01,
         1.94101603e-01,  1.33225943e-01],
       [ 3.34870598e-01, -4.16009689e-01, -1.28197243e+00,
         1.37235899e-01,  1.33225943e-01],
       [ 3.57965122e-01, -4.16009689e-01, -1.05056946e+00,
         3.64698715e-01,  1.75297293e-03],
       [ 3.81059646e-01,  3.10997534e-01, -1.24957601e-01,
         4.78430123e-01,  2.64698913e-01],
       [ 4.04154170e-01, -5.25060772e-02, -1.05056946e+00,
         1.37235899e-01,  1.75297293e-03],
       [ 4.27248694e-01, -1.02184904e+00, -1.74477836e+00,
        -2.60824029e-01, -2.61192967e-01],
       [ 4.50343218e-01, -2.94841818e-01, -8.19166497e-01,
         2.50967307e-01,  1.33225943e-01],
       [ 4.73437742e-01, -1.73673948e-01, -1.24957601e-01,
         2.50967307e-01,  1.75297293e-03],
       [ 4.96532266e-01, -1.73673948e-01, -3.56360566e-01,
         2.50967307e-01,  1.33225943e-01],
       [ 5.19626790e-01,  4.32165405e-01, -3.56360566e-01,
         3.07833011e-01,  1.33225943e-01],
       [ 5.42721314e-01, -9.00681170e-01, -1.28197243e+00,
        -4.31421141e-01, -1.29719997e-01],
       [ 5.65815838e-01, -1.73673948e-01, -5.87763531e-01,
         1.94101603e-01,  1.33225943e-01],
       [ 5.88910362e-01,  5.53333275e-01,  5.69251294e-01,
         1.27454998e+00,  1.71090158e+00],
       [ 6.12004886e-01, -5.25060772e-02, -8.19166497e-01,
         7.62758643e-01,  9.22063763e-01],
       [ 6.35099410e-01,  1.52267624e+00, -1.24957601e-01,
         1.21768427e+00,  1.18500970e+00],
       [ 6.58193934e-01,  5.53333275e-01, -3.56360566e-01,
         1.04708716e+00,  7.90590793e-01],
       [ 6.81288458e-01,  7.95669016e-01, -1.24957601e-01,
         1.16081857e+00,  1.31648267e+00],
       [ 7.04382982e-01,  2.12851559e+00, -1.24957601e-01,
         1.61574420e+00,  1.18500970e+00],
       [ 7.27477506e-01, -1.14301691e+00, -1.28197243e+00,
         4.21564419e-01,  6.59117823e-01],
       [ 7.50572030e-01,  1.76501198e+00, -3.56360566e-01,
         1.44514709e+00,  7.90590793e-01],
       [ 7.73666553e-01,  1.03800476e+00, -1.28197243e+00,
         1.16081857e+00,  7.90590793e-01],
       [ 7.96761077e-01,  1.64384411e+00,  1.26346019e+00,
         1.33141568e+00,  1.71090158e+00],
       [ 8.19855601e-01,  7.95669016e-01,  3.37848329e-01,
         7.62758643e-01,  1.05353673e+00],
       [ 8.42950125e-01,  6.74501145e-01, -8.19166497e-01,
         8.76490051e-01,  9.22063763e-01],
       [ 8.66044649e-01,  1.15917263e+00, -1.24957601e-01,
         9.90221459e-01,  1.18500970e+00],
       [ 8.89139173e-01, -1.73673948e-01, -1.28197243e+00,
         7.05892939e-01,  1.05353673e+00],
       [ 9.12233697e-01, -5.25060772e-02, -5.87763531e-01,
         7.62758643e-01,  1.57942861e+00],
       [ 9.35328221e-01,  6.74501145e-01,  3.37848329e-01,
         8.76490051e-01,  1.44795564e+00],
       [ 9.58422745e-01,  7.95669016e-01, -1.24957601e-01,
         9.90221459e-01,  7.90590793e-01],
       [ 9.81517269e-01,  2.24968346e+00,  1.72626612e+00,
         1.67260991e+00,  1.31648267e+00],
       [ 1.00461179e+00,  2.24968346e+00, -1.05056946e+00,
         1.78634131e+00,  1.44795564e+00],
       [ 1.02770632e+00,  1.89829664e-01, -1.97618132e+00,
         7.05892939e-01,  3.96171883e-01],
       [ 1.05080084e+00,  1.28034050e+00,  3.37848329e-01,
         1.10395287e+00,  1.44795564e+00],
       [ 1.07389537e+00, -2.94841818e-01, -5.87763531e-01,
         6.49027235e-01,  1.05353673e+00],
       [ 1.09698989e+00,  2.24968346e+00, -5.87763531e-01,
         1.67260991e+00,  1.05353673e+00],
       [ 1.12008441e+00,  5.53333275e-01, -8.19166497e-01,
         6.49027235e-01,  7.90590793e-01],
       [ 1.14317894e+00,  1.03800476e+00,  5.69251294e-01,
         1.10395287e+00,  1.18500970e+00],
       [ 1.16627346e+00,  1.64384411e+00,  3.37848329e-01,
         1.27454998e+00,  7.90590793e-01],
       [ 1.18936799e+00,  4.32165405e-01, -5.87763531e-01,
         5.92161531e-01,  7.90590793e-01],
       [ 1.21246251e+00,  3.10997534e-01, -1.24957601e-01,
         6.49027235e-01,  7.90590793e-01],
       [ 1.23555703e+00,  6.74501145e-01, -5.87763531e-01,
         1.04708716e+00,  1.18500970e+00],
       [ 1.25865156e+00,  1.64384411e+00, -1.24957601e-01,
         1.16081857e+00,  5.27644853e-01],
       [ 1.28174608e+00,  1.88617985e+00, -5.87763531e-01,
         1.33141568e+00,  9.22063763e-01],
       [ 1.30484061e+00,  2.49201920e+00,  1.72626612e+00,
         1.50201279e+00,  1.05353673e+00],
       [ 1.32793513e+00,  6.74501145e-01, -5.87763531e-01,
         1.04708716e+00,  1.31648267e+00],
       [ 1.35102965e+00,  5.53333275e-01, -5.87763531e-01,
         7.62758643e-01,  3.96171883e-01],
       [ 1.37412418e+00,  3.10997534e-01, -1.05056946e+00,
         1.04708716e+00,  2.64698913e-01],
       [ 1.39721870e+00,  2.24968346e+00, -1.24957601e-01,
         1.33141568e+00,  1.44795564e+00],
       [ 1.42031323e+00,  5.53333275e-01,  8.00654259e-01,
         1.04708716e+00,  1.57942861e+00],
       [ 1.44340775e+00,  6.74501145e-01,  1.06445364e-01,
         9.90221459e-01,  7.90590793e-01],
       [ 1.46650227e+00,  1.89829664e-01, -1.24957601e-01,
         5.92161531e-01,  7.90590793e-01],
       [ 1.48959680e+00,  1.28034050e+00,  1.06445364e-01,
         9.33355755e-01,  1.18500970e+00],
       [ 1.51269132e+00,  1.03800476e+00,  1.06445364e-01,
         1.04708716e+00,  1.57942861e+00],
       [ 1.53578584e+00,  1.28034050e+00,  1.06445364e-01,
         7.62758643e-01,  1.44795564e+00],
       [ 1.55888037e+00, -5.25060772e-02, -8.19166497e-01,
         7.62758643e-01,  9.22063763e-01],
       [ 1.58197489e+00,  1.15917263e+00,  3.37848329e-01,
         1.21768427e+00,  1.44795564e+00],
       [ 1.60506942e+00,  1.03800476e+00,  5.69251294e-01,
         1.10395287e+00,  1.71090158e+00],
       [ 1.62816394e+00,  1.03800476e+00, -1.24957601e-01,
         8.19624347e-01,  1.44795564e+00],
       [ 1.65125846e+00,  5.53333275e-01, -1.28197243e+00,
         7.05892939e-01,  9.22063763e-01],
       [ 1.67435299e+00,  7.95669016e-01, -1.24957601e-01,
         8.19624347e-01,  1.05353673e+00],
       [ 1.69744751e+00,  4.32165405e-01,  8.00654259e-01,
         9.33355755e-01,  1.44795564e+00],
       [ 1.72054204e+00,  6.86617933e-02, -1.24957601e-01,
         7.62758643e-01,  7.90590793e-01]])

In [62]:
from sklearn.preprocessing import Binarizer
df6=df.copy(deep=True)
x6=df6.iloc[:,0:5]
bin=Binarizer(threshold=3)
x6_Scaled=bin.fit_transform(x6)
x6_Scaled

array([[0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 0.]])