In [14]:
a=2
b=4
c=a+b
d=a-b
e=a*b
f=a/b
print(c)
print(d)
print(e)

6
-2
8

In [3]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("Iris_1.csv")

In [7]:
df.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            NaN           NaN  Iris-setosa
6   7            NaN           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           NaN            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [8]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [15]:
#initial inspection

df.shape

(150, 6)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  148 non-null    float64
 2   SepalWidthCm   147 non-null    float64
 3   PetalLengthCm  146 non-null    float64
 4   PetalWidthCm   144 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [19]:
df.head(12)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            NaN           NaN  Iris-setosa
6    7            NaN           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           NaN            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            NaN           3.4            1.6           0.2  Iris-setosa

In [21]:
df.tail(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [60]:
df.describe()
df.isna().sum()

Id                 0
SepalLengthCm    150
SepalWidthCm       3
PetalLengthCm      4
PetalWidthCm       6
Species            0
dtype: int64

In [62]:
df1=df.copy(deep=True)

In [64]:
print(df1.isna().sum())

Id                 0
SepalLengthCm    150
SepalWidthCm       3
PetalLengthCm      4
PetalWidthCm       6
Species            0
dtype: int64

In [66]:
df["SepalLengthCm"]=df["SepalLengthCm"].fillna(4.8,inplace=True)
df1.head(15)

C:\Users\ghane\AppData\Local\Temp\ipykernel_12084\704348039.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["SepalLengthCm"]=df["SepalLengthCm"].fillna(4.8,inplace=True)
C:\Users\ghane\AppData\Local\Temp\ipykernel_12084\704348039.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["SepalLengthCm"]=df["SepalLengthCm"].fillna(4.8,inplace=True)

    Id SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1          None           3.5            1.4           0.2  Iris-setosa
1    2          None           3.0            1.4           0.2  Iris-setosa
2    3          None           3.2            1.3           0.2  Iris-setosa
3    4          None           3.1            1.5           0.2  Iris-setosa
4    5          None           3.6            1.4           0.2  Iris-setosa
5    6          None           3.9            NaN           NaN  Iris-setosa
6    7          None           3.4            1.4           0.3  Iris-setosa
7    8          None           3.4            1.5           0.2  Iris-setosa
8    9          None           NaN            1.4           0.2  Iris-setosa
9   10          None           3.1            1.5           0.1  Iris-setosa
10  11          None           3.7            1.5           0.2  Iris-setosa
11  12          None           3.4            1.6           0.2  Iris-setosa
12  13          None           3.0            NaN           0.1  Iris-setosa
13  14          None           3.0            1.1           0.1  Iris-setosa
14  15          None           4.0            1.2           0.2  Iris-setosa

In [68]:
med=df1["SepalWidthCm"].median()
print(med)
df1["SepalWidthCm"]=df1["SepalWidthCm"].fillna(med)
df1.head(30)

3.0

    Id SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1          None           3.5            1.4           0.2  Iris-setosa
1    2          None           3.0            1.4           0.2  Iris-setosa
2    3          None           3.2            1.3           0.2  Iris-setosa
3    4          None           3.1            1.5           0.2  Iris-setosa
4    5          None           3.6            1.4           0.2  Iris-setosa
5    6          None           3.9            NaN           NaN  Iris-setosa
6    7          None           3.4            1.4           0.3  Iris-setosa
7    8          None           3.4            1.5           0.2  Iris-setosa
8    9          None           3.0            1.4           0.2  Iris-setosa
9   10          None           3.1            1.5           0.1  Iris-setosa
10  11          None           3.7            1.5           0.2  Iris-setosa
11  12          None           3.4            1.6           0.2  Iris-setosa
12  13          None           3.0            NaN           0.1  Iris-setosa
13  14          None           3.0            1.1           0.1  Iris-setosa
14  15          None           4.0            1.2           0.2  Iris-setosa
15  16          None           4.4            1.5           0.4  Iris-setosa
16  17          None           3.9            1.3           0.4  Iris-setosa
17  18          None           3.5            1.4           0.3  Iris-setosa
18  19          None           3.8            1.7           0.3  Iris-setosa
19  20          None           3.8            1.5           0.3  Iris-setosa
20  21          None           3.0            1.7           0.2  Iris-setosa
21  22          None           3.7            NaN           0.4  Iris-setosa
22  23          None           3.6            1.0           0.2  Iris-setosa
23  24          None           3.3            1.7           NaN  Iris-setosa
24  25          None           3.4            1.9           NaN  Iris-setosa
25  26          None           3.0            1.6           NaN  Iris-setosa
26  27          None           3.4            1.6           NaN  Iris-setosa
27  28          None           3.5            1.5           NaN  Iris-setosa
28  29          None           3.0            NaN           0.2  Iris-setosa
29  30          None           3.2            1.6           0.2  Iris-setosa

In [70]:
me=df1["PetalLengthCm"].mean()
print(me)
df1["PetalLengthCm"]=df1["PetalLengthCm"].fillna(me)
df1.head(15)

3.820547945205479

    Id SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1          None           3.5       1.400000           0.2  Iris-setosa
1    2          None           3.0       1.400000           0.2  Iris-setosa
2    3          None           3.2       1.300000           0.2  Iris-setosa
3    4          None           3.1       1.500000           0.2  Iris-setosa
4    5          None           3.6       1.400000           0.2  Iris-setosa
5    6          None           3.9       3.820548           NaN  Iris-setosa
6    7          None           3.4       1.400000           0.3  Iris-setosa
7    8          None           3.4       1.500000           0.2  Iris-setosa
8    9          None           3.0       1.400000           0.2  Iris-setosa
9   10          None           3.1       1.500000           0.1  Iris-setosa
10  11          None           3.7       1.500000           0.2  Iris-setosa
11  12          None           3.4       1.600000           0.2  Iris-setosa
12  13          None           3.0       3.820548           0.1  Iris-setosa
13  14          None           3.0       1.100000           0.1  Iris-setosa
14  15          None           4.0       1.200000           0.2  Iris-setosa

In [72]:
df1.isna().sum()

Id                 0
SepalLengthCm    150
SepalWidthCm       0
PetalLengthCm      0
PetalWidthCm       6
Species            0
dtype: int64

In [73]:
df1.dropna(inplace=True)
df1.head(10)

Empty DataFrame
Columns: [Id, SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, Species]
Index: []

In [74]:
df1.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64