In [4]:
#defining libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,accuracy_score
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix

In [5]:
df=pd.read_csv("example.csv")

In [6]:
df.head()

,Student Name,Student ID,Class,Section,Attendance Status,Attendance Marked By
0,Komal Chavhan,1,5,A,Present,Ms. Johnson
1,Maheshwari Citewar,2,6,B,Absent,Mr. Brown
2,Akshay Chavan,3,4,C,Late,Ms. White
3,Nilakshi Chandatre,4,7,A,Present,Mr. Green
4,Vrushali Gil,5,5,B,Excused,Ms. Black

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Student Name          32 non-null     object
 1   Student ID            32 non-null     int64
 2   Class                 32 non-null     int64
 3   Section               32 non-null     object
 4   Attendance Status     32 non-null     object
 5   Attendance Marked By  32 non-null     object
dtypes: int64(2), object(4)
memory usage: 1.6+ KB

In [8]:
df.shape

(32, 6)

In [9]:
df.describe()

       Student ID      Class
count   32.000000  32.000000
mean    16.500000   5.500000
std      9.380832   1.016001
min      1.000000   4.000000
25%      8.750000   5.000000
50%     16.500000   5.500000
75%     24.250000   6.000000
max     32.000000   7.000000

In [10]:
df.isna().sum()

Student Name            0
Student ID              0
Class                   0
Section                 0
Attendance Status       0
Attendance Marked By    0
dtype: int64

In [11]:
le=LabelEncoder()
cols={"Attendance Status","Student Name","Section","Attendance Marked By"}
for f in cols:
    df[f]=le.fit_transform(df[f])

In [12]:
df.head()

,Student Name,Student ID,Class,Section,Attendance Status,Attendance Marked By
0,15,1,5,0,3,8
1,16,2,6,1,0,1
2,4,3,4,2,2,9
3,17,4,7,0,3,2
4,29,5,5,1,1,5

In [13]:
df.corr()

,Student Name,Student ID,Class,Section,Attendance Status,Attendance Marked By
Student Name,1.000000,0.046554,-0.209843,0.185811,-0.148335,-0.004644
Student ID,0.046554,1.000000,0.047384,0.016517,0.006054,-0.068493
Class,-0.209843,0.047384,1.000000,-0.419371,0.335410,-0.803900
Section,0.185811,0.016517,-0.419371,1.000000,-0.204598,0.065383
Attendance Status,-0.148335,0.006054,0.335410,-0.204598,1.000000,-0.258851
Attendance Marked By,-0.004644,-0.068493,-0.803900,0.065383,-0.258851,1.000000

In [16]:
x=df[["Student ID"]]
y=df[["Student Name"]]

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [28]:
slr=LinearRegression()
slr.fit(x_train,y_train)
slr.coef_

array([[0.05546466]])

In [30]:
ypred=slr.predict(x_test)
ypred

array([[14.97742147],
       [13.86812827],
       [15.14381545],
       [14.53370419],
       [15.4766034 ],
       [14.36731021],
       [13.92359293]])

In [32]:
r2_score(y_test,ypred)

-0.3613892276647135

In [270]:
x_new=np.array([5000]).reshape(1,-1)
slr.predict(x_new)

C:\Users\ghane\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[291.13596204]])

In [272]:
knn=KNeighborsClassifier(n_neighbors=3,metric='euclidean')
knn.fit(x_train,y_train)

C:\Users\ghane\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

In [274]:
ypred=knn.predict(x_test)
ypred

array([ 5,  4,  1,  6, 14,  0,  4], dtype=int64)

In [276]:
accuracy_score(y_test,ypred)

0.0

In [278]:
df.head(30)

,Student Name,Student ID,Class,Section,Attendance Status,Attendance Marked By
0,15,1,5,0,3,8
1,16,2,6,1,0,1
2,4,3,4,2,2,9
3,17,4,7,0,3,2
4,29,5,5,1,1,5
5,10,6,6,0,3,4
6,30,7,4,2,0,6
7,0,8,7,1,3,0
8,3,9,5,0,2,7
9,28,10,6,2,3,3
10,31,11,5,0,2,8
11,7,12,6,1,3,1
12,13,13,4,2,1,9
13,6,14,7,0,3,2
14,18,15,5,1,0,5
15,12,16,6,0,3,4
16,22,17,4,2,2,6
17,25,18,7,1,3,0
18,9,19,5,0,1,7
19,5,20,6,2,3,3
20,20,21,5,0,0,8
21,21,22,6,1,3,1
22,8,23,4,2,2,8
23,11,24,7,0,3,1
24,1,25,5,1,1,9
25,19,26,6,0,2,2
26,27,27,4,2,3,5
27,14,28,7,1,1,4
28,23,29,5,0,3,6
29,24,30,6,2,0,0

In [280]:
classifier=LinearSVC()
classifier.fit(x_train,y_train)

C:\Users\ghane\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LinearSVC()

In [281]:
ypred=classifier.predict(x_test)
ypred

array([2, 4, 2, 7, 2, 3, 4], dtype=int64)

In [284]:
accuracy_score(y_test,ypred)

0.0

In [288]:
confusion_matrix(y_test,ypred)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [290]:
df.columns

Index(['Student Name', 'Student ID', 'Class', 'Section', 'Attendance Status',
       'Attendance Marked By'],
      dtype='object')